### ISSUE TITLE
[Tracking issue] Initial inventory of elements, components and modules

### ISSUE THREAD

**Issue by fnune** [fnune/janina#2]
### Elements

- [x] Buttons (primary, secondary, text) (idle, hover, active, disabled, loading) https://github.com/fnune/janina/pull/9
- [x] Radio buttons (checked, unchecked) (idle, hover, active, disabled, loading) https://github.com/fnune/janina/pull/14
- [x] Checkboxes (checked, unchecked) (idle, hover, active, disabled, loading) https://github.com/fnune/janina/pull/13
- [ ] Slider checkboxes (checked, unchecked) (idle, hover, active, disabled, loading)
- [ ] Tag (idle, hover, active, disabled, loading)
- [x] Input (idle, hover, focus, disabled) (prefix, suffix) https://github.com/fnune/janina/pull/10
- [x] Textarea
- [ ] File upload
- [ ] Badge
- [x] Content https://github.com/fnune/janina/pull/11
- [ ] Progress bar (empty, in progress, done)
- [ ] Progress circle (empty, in progress, done)
- [ ] Indefinite loader (idle, loading)
- [ ] List
- [ ] Image
- [x] Tooltip https://github.com/fnune/janina/pull/16
- [x] Card https://github.com/fnune/janina/pull/12
- [x] Select

### Components

TBA

### Modules

TBA
